spring:
  datasource:
    # 开发环境配置
    url: jdbc:p6spy:mysql://106.53.65.162:3306/blog_dev?serverTimezone=GMT%2B8
    username: blog_dev
    password: pWjxcECjBJ2zaBS6
    schema: classpath:db/schema.sql
    data: classpath:db/data.sql
    initialization-mode: never
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
  redis:
    host: 106.53.65.162
    port: 6379
    password: 123456
    jedis:
      pool:
        max-wait: 30000ms # 连接池最大阻塞时间
        max-active: 100 # 连接池最大连接数
        max-idle: 20 # 连接池中的最大空闲连接
        min-idle: 0 # 连接池中的最小空闲连接
    timeout: 10000ms # 连接超时

wx:
  certPath: D:/wx/WXCertUtil/cert/
  payNoticePath: http://dev.blog.com/blog/WXPay/payNotify
  refundPath: http://dev.blog.com/abjy/blog/refundNotify